### ISSUE TITLE
Unfortunately it doesn't work for me

### ISSUE THREAD

**Issue by Wikunia** [beldar/Auto-Brackets#1]
Hi,
I like the idea to close the bracket only if I want to so no autoclosing tags.
But unfortunately it doesn't work on my Win 8.1 machine Brackets v.39
There are no errors in the developer tools.

**Comment by beldar** [comment]
Hi Wikunia, unfortunately I had no time to test it on Windows, but I will as soon as I can, thanks for reporting it.

Have you tried, closing and opening again Brackets? Also in which kind of file did you test it, did you test in a Javascript file?

**Comment by Wikunia** [comment]
I restart it two times and I tested it only in php files I thought it should work in all file types :)
Ah okay it work in JS files! Thx

**Comment by beldar** [comment]
I also thought it worked on all file types, I have to debug further. Sorry!

**Comment by Wikunia** [comment]
Okay make a small comment here if you updated it! ;)
