### ISSUE TITLE
Vertical lines

### ISSUE THREAD

**Issue by Hova10** [beldar/Auto-Brackets#3]
Hey,
I don't have an issue with your extension, since it's working perfectly (thank you for that btw), but i was just wondering if you could tell me what's the extension you're using to have the vertical lines appear when you hit enter. You know, the ones that "connect" the starting and ending "tags". I tried searching on the extension manager but i must have missed it...

Sry for creating an issue just to ask you this, but i'm new to github so i have no idea on how to contact you privately to ask you this.
Tyvm in advance.

**Comment by beldar** [comment]
Hi @Hova10 , the extension is called Indent Guides, you can find it inside the extension manager on Brackets, or here: https://github.com/lkcampbell/brackets-indent-guides

Cheers!

**Comment by Hova10** [comment]
Thx alot mate. Really apreciate it...
